//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC_L55_VALIDN_EF_28523.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblRegistration
    {
        public int rid { get; set; }

        [Required(ErrorMessage ="Please enter your name !!")]
        public string name { get; set; }

        [Required(ErrorMessage = "Please enter your email !!")]
        public string email { get; set; }

        [Required(ErrorMessage = "Please enter your password !!")]
        public string password { get; set; }

        [Required(ErrorMessage = "Please enter your age !!")]
        public Nullable<int> age { get; set; }
    }
}
