//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC_L54_JOIN_EF_28523.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public int cid { get; set; }
        public string cname { get; set; }
    }
}
